#### Notes, 

This is to test the library of quantum simulations and to have the tensor multiplication library to execute Jordan Wigner transformation. 

In [2]:
using Plots
using LinearAlgebra
using SparseArrays
using Printf
using TensorOperations
using Tensorial 

In [4]:
include("quantum_gates.jl")
using ..quantum_gates: Qgate
include("quantum_circuit.jl")
using ..quantum_circuit: qc_initialize
include("conventions.jl")
using ..conventions: conventions


Load quantum gates constructor


Load quantum gates constructor
Load quantum gates constructor


In [ ]:
include("QTensor.jl")
using ..QTensor: Qgate_T2D

In [ ]:

show(stdout, "text/plain", Qgate.CCX(3,2,1))

In [ ]:
versioninfo()

In [ ]:
show(stdout, "text/plain", one(Tensor{Tuple{3,3}}))

In [ ]:
N = 100
A = randn(N,N);
B = randn(N,N);
As = sparse(A);
Bs = sparse(B);

In [ ]:
gate_construct=1
@time kron(As, Bs)
@time kron(A, B)
#kron(gate, gate_construct)

In [ ]:
gate = Qgate.H
L = Qgate_T2D(gate, 1, 2)


In [ ]:
show(stdout, "text/plain", L)

In [ ]:
for i in 0:3
    println(i)
end

In [28]:
gate_construct

4×4 Matrix{Float64}:
 1.0  0.0   1.0   0.0
 0.0  1.0   0.0   1.0
 1.0  0.0  -1.0  -0.0
 0.0  1.0  -0.0  -1.0

In [22]:
nqubits_convention

1

In [5]:
gate = Qgate.H
gate_construct = 1
II = Matrix(I, 2, 2)
for i in 0:1
if i == 1
gate_construct = kron(gate, gate_construct)
else
gate_construct = kron(II, gate_construct)
end
end

In [6]:
gate_construct

4×4 Matrix{Float64}:
 1.0  0.0   1.0   0.0
 0.0  1.0   0.0   1.0
 1.0  0.0  -1.0  -0.0
 0.0  1.0  -0.0  -1.0

In [7]:
gate = Qgate.H


2×2 Matrix{Float64}:
 1.0   1.0
 1.0  -1.0

In [35]:
println(Qgate_T2D(gate, 1, 3))

[1.0 0.0 1.0 0.0 0.0 0.0 0.0 0.0; 0.0 1.0 0.0 1.0 0.0 0.0 0.0 0.0; 1.0 0.0 -1.0 -0.0 0.0 0.0 -0.0 -0.0; 0.0 1.0 -0.0 -1.0 0.0 0.0 -0.0 -0.0; 0.0 0.0 0.0 0.0 1.0 0.0 1.0 0.0; 0.0 0.0 0.0 0.0 0.0 1.0 0.0 1.0; 0.0 0.0 -0.0 -0.0 1.0 0.0 -1.0 -0.0; 0.0 0.0 -0.0 -0.0 0.0 1.0 -0.0 -1.0]


In [21]:

# function to print a quantum register and quantum states in latex format 
function print_statevector(
    state_vector::Union{Vector{Float64}, Vector{Int64}, Vector{ComplexF64}},
    q_states::Array{Int64,2})
    # print a quantum register and quantum states in latex format 
    # qc::qc_initstruct: quantum register
    # return: print a quantum register and quantum states in latex format 

    # combine statevector and quantum states in one table 
    # state_vector::Vector{ComplexF64}: statevector of the quantum register
    # q_states::Array{Int64,2}: quantum states of the quantum register
    # return: print a quantum register and quantum states in latex format
    qtab = [q_states convert(Array{Int64}, state_vector)]
    println("The quantum register and quantum states in latex format are: ")
    show(stdout, "text/plain", qtab)
end # end print_latex

print_statevector (generic function with 2 methods)

In [37]:
https://lewisla.gitbook.io/learning-quantum/quantum-circuits/multi-qubit-gates

ErrorException: syntax: "//" is not a unary operator

In [38]:
qreg,qtab,nbas,n_dim,q_order = quantum_circuit.init_register(2)
show(stdout, "text/plain", qtab)
println("                  ")
show(stdout, "text/plain", qreg)
qtab2 = [state_vector convert(Array{Int64,2}, q_states)]
show(stdout, "text/plain", qtab2)

4×2 Matrix{Float64}:
 0.0  0.0
 0.0  1.0
 1.0  0.0
 1.0  1.0                  
4-element Vector{Float64}:
 0.0
 0.0
 0.0
 0.04×3 Matrix{Float64}:
 0.0  0.0  0.0
 0.0  0.0  1.0
 0.0  1.0  0.0
 0.0  1.0  1.0

In [9]:
## test
# qubits in the quantum register with state |0> or |1>
# initialize state |0> 
q0_0 = [1; 0];
q1_0 = [1; 0];

# initialize state |1>
q0_1 = [0; 1];
q1_1 = [0; 1];


II = Matrix(I, 2, 2)
qq = kron(q0_0, q1_0)
show(stdout, "text/plain", qq)
s1 = q0*q1'
show(stdout, "text/plain", s1)
show(stdout, "text/plain", II)

s2 = kron(s1, II)
show(stdout, "text/plain", s2)

s3 = q0_1*q1_1' 
show(stdout, "text/plain", s3)
s = kron(q0_0*q1_0',II) + kron(q0_1*q1_1',Qgate.X) 

4-element Vector{Int64}:
 1
 0
 0
 0

UndefVarError: UndefVarError: `q0` not defined

In [17]:
show(stdout, "text/plain", q1)

2-element Vector{Int64}:
 1
 0

In [10]:
UX = [0 1; 1 0]

nqubits = 2
qubit_control_1 = 0
#qubit_control_2 = 1
qubit_target = 1
II = Matrix(I, 2, 2) # indentity matrix
# initiate the matrix out of the loop

# build the density matrix of the quantum register for state |00>
q0 = [1; 0]
q1 = [1; 0]
q1_1 = [0;1]
q1_0 = [1;0]
rho_00 = q1_0*q1_0'
rho_11 = q1_1*q1_1'



2×2 Matrix{Int64}:
 0  0
 0  1

In [11]:
U2D_term = zeros(4,4)
U2D_term = kron(rho_00, II)
U2D_term = kron(rho_11, U2D)

UndefVarError: UndefVarError: `U2D` not defined

In [12]:
U2D = zeros(4,4)

for iq in 0:nqubits-1
    U2D_term = zeros(4,4)
    if iq == qubit_control_1
      U2D_term = kron(rho_00, II)
    elseif iq == qubit_target
      U2D_term = kron(rho_11, UX)
    else
      U2D_term = kron(II, II)
    end
    U2D = U2D + U2D_term
  end

In [13]:
U2D

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  1.0  0.0  0.0
 0.0  0.0  0.0  1.0
 0.0  0.0  1.0  0.0

In [14]:
U2D = zeros(4,4)

for iq in 0:nqubits-1
    U2D_term = zeros(4,4)
    if iq == qubit_control_1
      U2D_term = kron(II,rho_00)
    elseif iq == qubit_target
      U2D_term = kron(UX, rho_11 )
    else
      U2D_term = kron(II, II)
    end
    U2D = U2D + U2D_term
  end

In [15]:
U2D

4×4 Matrix{Float64}:
 1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0
 0.0  0.0  1.0  0.0
 0.0  1.0  0.0  0.0

In [17]:
UX = [0 1; 1 0]

nqubits = 3
qubit_control_1 = 0
qubit_control_2 = 1
qubit_target = 1
II = Matrix(I, 2, 2) # indentity matrix
# initiate the matrix out of the loop

# build the density matrix of the quantum register for state |00>
q0_0 = [1; 0]
q0_1 = [0; 1]
rho_00 = q0_0*q0_0'
rho_11 = q0_1*q0_1'

U2D_term = zeros(2^nqubits,2^nqubits)


8×8 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

In [ ]:
nqubits = 3
qubit_control_0 = 0
qubit_control_1 = 1
qubit_target = 2
II = Matrix(I, 2, 2) # indentity matrix
# initiate the matrix out of the loop

# build the density matrix of the quantum register for state |00>
q0_0 = [1; 0]
q0_1 = [0; 1]
q1_0 = [1; 0]
q1_1 = [0; 1]
q2_0 = [1; 0]
q2_1 = [0; 1]
rho_00 = q0_0*q0_0'
rho_11 = q0_1*q0_1'

U2D = zeros(8,8)
for iq in 0:nqubits-1
    U2D_term = zeros(8,8)
    if iq == qubit_control_0
      # multiply using tensors the rest of qubits 
      tab = []
      
      
    elseif iq == qubit_control_1
        U2D_term = kron(rho_00,II)
    elseif iq == qubit_target
      U2D_term = kron(UX, rho_11 )
    else
      U2D_term = kron(II, II)
    end
    U2D = U2D + U2D_term
  end

In [18]:
kron(rho_00,II,II)

8×8 Matrix{Int64}:
 1  0  0  0  0  0  0  0
 0  1  0  0  0  0  0  0
 0  0  1  0  0  0  0  0
 0  0  0  1  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0
 0  0  0  0  0  0  0  0